export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS';
export const DELETE_PROFILE_DETAILS = 'DELETE_PROFILE_DETAILS';
export const SET_BMR_DETAILS = 'SET_BMR_DETAILS';
export const SET_CHANGE_IN_WEIGHT_DETAILS = 'SET_CHANGE_IN_WEIGHT_DETAILS';
export const SET_NEW_BMR = 'SET_NEW_BMR';
export const CLEAR_NEW_BMR = 'CLEAR_NEW_BMR';
